name: CI and CD
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  lint:
    name: Run ESLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'
      - name: Setup Node.js with Volta
        uses: ./.github/actions/setup-node
      - name: Run ESLint
        run: yarn lint
  format:
    name: Run Prettier
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'
      - name: Setup Node.js with Volta
        uses: ./.github/actions/setup-node
      - name: Run Prettier
        run: yarn format
  test:
    name: Run Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'
      - name: Setup Node.js with Volta
        uses: ./.github/actions/setup-node
      - name: Run coverage tests
        run: yarn test:coverage
      - name: Edit result file
        run: tail -n +2 coverage/result-jest.txt | head -n -1 > result.txt
      - name: Write coverages to summary
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require("fs").promises;
            const jest = await fs.readFile("./result.txt").then((b) => b.toString());
            const output = `\n${jest}`;
            await core.summary
              .addHeading('Jest Coverages')
              .addRaw(output)
              .write();
  build:
    name: Run Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'
      - name: Setup Node.js with Volta
        uses: ./.github/actions/setup-node
      - name: Restore Next.js build cache
        uses: actions/cache@v3
        with:
          path: |
            .next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/yarn.lock') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          restore-keys: ${{ runner.os }}-nextjs-${{ hashFiles('**/yarn.lock') }}-
      - name: Make envfile
        run: |
          cat > .env <<EOD
          NODE_ENV=${{ vars.NODE_ENV }}
          NEXT_PUBLIC_BACKEND_API_URL=${{ secrets.NEXT_PUBLIC_BACKEND_API_URL }}
          NEXT_PUBLIC_MS_APP_CLIENT_ID=${{ secrets.NEXT_PUBLIC_MS_APP_CLIENT_ID }}
          NEXT_PUBLIC_MS_APP_REDIRECT_URL=${{ vars.NEXT_PUBLIC_MS_APP_REDIRECT_URL }}
          EOD
      - name: Run build
        run: yarn build
      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_PAGES_API_TOKEN }}
          accountId: 9e9e88e2b19878c4a911c3c8a715a168
          projectName: seichi-portal
          directory: out
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
