name: CI and CD
on:
  push:
    branches:
      - main
  workflow_dispatch:
concurrency:
  group: pages
  cancel-in-progress: true
jobs:
  ci:
    name: CI
    uses: ./.github/workflows/ci.yml
  upload:
    name: Upload artifacts
    runs-on: ubuntu-latest
    needs:
      - ci
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: nextjs-out
      - name: Upload artifacts for GitHub Pages
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./out
  deploy:
    name: Deploy artifacts to GitHub Pages
    runs-on: ubuntu-latest
    needs:
      - upload
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
