name: CI and CD
on:
  push:
    branches:
      - main
  workflow_dispatch:
concurrency:
  group: pages
  cancel-in-progress: true
env:
  NODE_ENV: ${{ vars.NODE_ENV }}
  NEXT_PUBLIC_BACKEND_API_URL: ${{ secrets.NEXT_PUBLIC_BACKEND_API_URL }}
  NEXT_PUBLIC_MS_APP_CLIENT_ID: ${{ secrets.NEXT_PUBLIC_MS_APP_CLIENT_ID }}
  NEXT_PUBLIC_MS_APP_REDIRECT_URL: ${{ vars.NEXT_PUBLIC_MS_APP_REDIRECT_URL }}
jobs:
  ci:
    name: CI
    uses: ./.github/workflows/ci.yml
  deploy:
    name: Deploy artifacts to GitHub Pages
    runs-on: ubuntu-latest
    needs:
      - ci
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
