name: CI
on:
  workflow_call:
  pull_request:
    branches:
      - main
jobs:
  lint:
    name: Run ESLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'
      - name: Setup Node.js
        uses: ./.github/actions/setup-node
      - name: Run ESLint
        run: yarn lint
  format:
    name: Run Prettier
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'
      - name: Setup Node.js
        uses: ./.github/actions/setup-node
      - name: Run Prettier
        run: yarn format
  test-jest:
    name: Run Test by Jest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'
      - name: Setup Node.js
        uses: ./.github/actions/setup-node
      - name: Run coverage tests by Jest
        run: yarn test:coverage
  test-storybook:
    name: Run Test by Storybook
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'
      - name: Setup Node.js
        uses: ./.github/actions/setup-node
      - name: Build Storybook
        run: yarn sb:build
      - name: Serve Files
        uses: Eun/http-server-action@v1.0.6
        with:
          directory: storybook-static
          port: 9001
      - name: Run tests by Storybook
        run: yarn sb:test:run
  build:
    name: Run Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'
      - name: Setup Node.js
        uses: ./.github/actions/setup-node
      - name: Restore Next.js build cache
        uses: actions/cache@v3
        with:
          path: |
            .next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/yarn.lock') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          restore-keys: ${{ runner.os }}-nextjs-${{ hashFiles('**/yarn.lock') }}-
      - name: Run build
        run: yarn build
      - name: Upload artifacts for GitHub Pages
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./out
