name: CI
on:
  workflow_call:
  pull_request:
    paths-ignore:
      - README.md
      - LICENSE
      - CODEOWNERS
      - renovate.json
jobs:
  lint:
    name: Run ESLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'
      - name: Setup Node.js with Volta
        uses: ./.github/actions/setup-node
      - name: Run ESLint
        run: yarn lint
  format:
    name: Run Prettier
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'
      - name: Setup Node.js with Volta
        uses: ./.github/actions/setup-node
      - name: Run Prettier
        run: yarn format
  test:
    name: Run Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'
      - name: Setup Node.js with Volta
        uses: ./.github/actions/setup-node
      - name: Run test
        run: yarn test
